### ISSUE TITLE
Question of Unity in MacOS

### ISSUE THREAD

**Issue by Yuhuoo** [aras-p/UnityGaussianSplatting#110]
Why the splat script component displayed is gray here?

<img width="1275" alt="image" src="https://github.com/aras-p/UnityGaussianSplatting/assets/91204817/23c8c6b7-a825-4872-ad5d-ff7b3d4d8e4b">

**Comment by Yuhuoo** [comment]
How to point the Asset field to one of your created assets ?

**Comment by aras-p** [comment]
First question: because you do not have a game object selected. You can only add components to game objects, whereas you have selected a folder, it seems.

Second question: first create a game object and add the component to it. Then the inspector (which is not even displayed/present in your unity layout?!) should show the settings, of which one will be the asset.

All of this sounds like "how to unity" in general questions, TBH. "Maybe first learn Unity a bit" would be my suggestion.

**Comment by Yuhuoo** [comment]
Thanks for your reply, and I have render the scence successfully.
But I can't editor the scene, and move the camera to watch the whole scene.
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/91204817/f34ce85d-d26a-4507-a912-6a7f5e54f4a4)

**Comment by aras-p** [comment]
You seem to be looking at the Game view, not the Scene view. The editing tools would be in the Scene view, where you can manipulate the objects and so on.

Again, all of this sounds like you should learn how to use Unity in the first place.

**Comment by iantv** [comment]
@aras-p you are so patient
