### ISSUE TITLE
Support for mobile device

### ISSUE THREAD

**Issue by ClimberHJX** [aras-p/UnityGaussianSplatting#117]
Can it support running on mobile devices? 
If not, can you provide some guidance on how to adapt it for mobile devices?

Thanks

**Comment by aras-p** [comment]
Depends on what you mean by "mobile", since there's a massive variation in device capabilities and performances. While I have not tested on _any_ mobile device, I suspect that things might "just work" on a modern iOS device (e.g. iPhone 14/15), and perhaps on a similarly modern Android device when using Vulkan graphics API. It is very possible that things do not work on older devices, but I both do not have the devices around me to test on, and don't have time to implement support for them. Sorry!
