### ISSUE TITLE
Rendering artifacts close to the splats

### ISSUE THREAD

**Issue by kennux** [aras-p/UnityGaussianSplatting#147]
There seems to be some instability in splat size and rotation when getting quite close to splats. I've tried to debug this but could not really pinpoint the exact issue. I've tested this in another tool I developed using the Inria SIBR CUDA renderer and there is a pretty similar effect.

I've recorded what exactly happens first with normal opacity and then with opacity scaled by 20:

https://github.com/user-attachments/assets/cc0b95ef-172a-43ad-b841-9f6462497b15

It seems to me like this issue is generally known with Gaussian Splats and there's also some code apparently that tries to make this less impactful in DecomposeCovariance (limit maxSize) and CalcCovariance2D (limX/limY size limit clamping).

However I haven't yet found a way to fully resolve this, is there anything that could help me mitigate or even solve this issue?
Thanks in advance!

**Comment by aras-p** [comment]
My implementation here is "just" the vanilla 3DGS, as described in the initial 3DGS paper. I believe various people have developed various improvements in the two years since the initial paper came out, some of them might be for solving issues like that.

If someone wants to contribute improvements in any way, either based on these follow-up papers, or discovered independently, I'll gladly take a look. But as the project readme says, I'm no longer following the 3DGS research & happenings, and I'm not planning on making significant improvements for this project myself.
