### ISSUE TITLE
Performance: investigate faster sorting options

### ISSUE THREAD

**Issue by aras-p** [aras-p/UnityGaussianSplatting#48]
Currently splat sorting uses AMD Fidelity FX based radix sorting. I actually have no idea how "good" or state-of-the-art it is, but some other options might be worth looking into:

- Alter the same sorting routine to not sort on full 32 bits of depth -- maybe 16, 20 or 24 bits would be just fine, especially if depth is quantized to be only within object's range. The current sort code is doing 4 bit radix rounds, so that would cut down on the number of rounds it does.
- Look into other sorting approaches. State of the art seems to be OneSweep radix sort, but that one might not work on all platforms (I think due to lack of `globallycoherent` on Metal?), plus most implementations of it seem to be hardcoded to nvidia SIMD width.

**Comment by b0nes164** [comment]
Hi @aras-p I'm the author of the OneSweep implementation for Unity.

It should be relatively simple to make a generalized version of my code that would support both Nvidia and AMD hardware. As for Metal, an older technique, _reduce-then-scan_ can be used, which, based on my own testing in CUDA, is about 85% the performance of OneSweep. Regardless, it would still be significantly faster than Fidelity FX due to the 8-bit radix. 

I'm not sure if maintaining multiple shader variants for different platforms is feasible, but if you're interested I would love to contribute. Currently, I am currently working on implementing [DietGPU](https://github.com/facebookresearch/dietgpu) in compute shaders, which is GPU based ANS compression, and could possibly be useful in piping data to the GPU.

**Comment by b0nes164** [comment]
I still need to test on AMD but preliminary results on iteration_30000 bicycle medium asset preset, indicate about a ~30% framerate increase. On my 2080 super I went from about ~70 fps to about ~95 fps. You can use performance uplift in the following frame nsight frame captures:
 
 Previous:
 ![FidelityFx](https://github.com/aras-p/UnityGaussianSplatting/assets/68340554/1e994355-9c1e-46c0-bee0-a1bb1f6280aa)
 
 New:
![DeviceRadixFrame](https://github.com/aras-p/UnityGaussianSplatting/assets/68340554/6fd8649f-ef12-4a3e-849e-26e3b2a36ff1)

Honestly, I don't have very much experience debugging shaders, so my integration testing was very janky--I basically dispatched the sorting routine immediately during the `GpuSorter.dispatch` function call instead of through the command buffer. Then I checked if whatever was in the `srcKeyBuffer` at the time was sorted correctly, so it will definitely need more testing, but the image ***appears*** to be free from visual artifacts. 

I can make a pull request now if you want to try it out yourself on a beta branch while I begin testing on AMD hardware.

**Comment by aras-p** [comment]
Implemented by #82
