### ISSUE TITLE
Converting Shaders to Shader Graph

### ISSUE THREAD

**Issue by antoniohof** [aras-p/UnityGaussianSplatting#71]
Hello,

I'm interested in building for the visionOS, but custom shaders are not compatible with this platform.

Do you know if there is any way of converting the current shaders to a shadergraph?

**Comment by aras-p** [comment]
Converting shaders to shadergraph might be doable, but the other missing bits would be compute shaders (required for sorting, plus caching some view data for performance). I've no idea if visionOS supports those.

**Comment by andybak** [comment]
There's a big distinction in VisionOS between the mixed reality apps (which are very restricted in what they can do) and VR apps (I think the call them "fully immersive" because they don't want to use the term "VR")

The latter has much more freedom in terms of functionality. I work on Open Brush and we don't envisage a huge issue porting to VisionOS. I don't remember the exact limitations but they were doable for us so I suspect they are doable for this project too. I'll report back when I find the details.

**Comment by andybak** [comment]
In terms of supporting mixed reality mode - that will be harder but this @keijiro repo shows a potential path forward: https://github.com/keijiro/SplatVFX

Even if VFX Graph isn't supported then his shaders (which only use the first spherical harmonic I think) might be useful.

Also - sorting in a compute shader can be avoided entirely if there's support for Stochastic OIT (order independent transparency) which I think looks fairly good if you can use MSAA and SV_COVERAGE masks.

**Comment by aras-p** [comment]
Yeah I have a branch where I'm experimenting with OIT via stochastic alpha test, maybe someday I should finish that and have that as an option.
