### ISSUE TITLE
Even faster radix sort :)

### ISSUE THREAD

**Issue by LifeIsStrange** [aras-p/UnityGaussianSplatting#77]
Hi @aras-p 
I think that leveraging fidelityFX radix sort is a great idea, as gpuopen is full of little known gems.
**however** despite this efficient library, it seems that sorting is still a major bottleneck
> cf 4.55ms rendering, 2.37ms **sorting**

BUT there happen to be a significantly faster radix sort out there, in fact it is likely to be the fastest GPU radix sort in the world:
https://arxiv.org/abs/2206.01784
and an open source implementation here:
https://github.com/b0nes164/ShaderOneSweep

This holds the promise for much better performance, however the current open source implementation is only supported for Nvidia cards (although finetuning for AMD could be done cf readme)
Hence you could either conditionally use this radix sort if nvidia hardware is detected, or port the library to other hardware.
Another limitation is that it is directx12 only so again conditional execution albeit it could probably be ported to Vulkan
**however** surprisingly enough, dirextx12 is well supported nowadays on linux, via wine/vkd3d, which is an efficient and mature automated mapping to vulkan https://github.com/HansKristian-Work/vkd3d-proton

**Comment by aras-p** [comment]
I'm aware of OneSweep sort, but did not put it in primarily because of "nvidia only" dependency. On some hardware (Apple GPUs) it can't work at all in principle, due to lack of globallycoherent feature, is my understanding -- it's not a matter of "porting", but rather that the whole algorithm does not work.

Anyway, I don't plan to put this in anytime soon. "Maybe someday", but very unspecified if that ever happens. If someone submits a PR that makes it happen, great, otherwise I'm closing this issue.

> Another limitation is that it is directx12 only

It's not. Since it's in Unity, it "should work" on Vulkan as well.
